### ISSUE TITLE
Initial Geonames exploration

### ISSUE THREAD

**Issue by mindrones** [nestauk/ontologies#1]
We need to collect queries and results in a dir tree like:

```
ontologies/
  geonames/
    cities.sparql
    cities.csv
    countries.sparql
    countries.csv
    ...
```

Queries are being discussed internally, we'll add more later.

**Comment by doogyb** [comment]
I'm wondering if it might make more sense to separate the queries and their results into two different directories?

```
ontologies/
  geonames/
    queries/
        cities.rq
        countries.rq
    results/
        cities.rq
        countries.csv
    ...
```

**Comment by mindrones** [comment]
We ended up deciding to use something like this to facilitate scripting in the [stress testing issue](https://github.com/nestauk/ontologies/issues/2):

```
ontologies/
	geonames/
		queries/
			stress/
			explore/
		results/
			stress/
			explore/
	MeSH/
	...
```
