### ISSUE TITLE
Investigate ingesting Openstreetmap

### ISSUE THREAD

**Issue by mindrones** [nestauk/ontologies#13]
- https://wiki.openstreetmap.org/wiki/OSM_Semantic_Network (seems quite old)
- https://github.com/GeoKnow/LinkedGeoData:
	- repo seems more recent (commits are 5 months old)
	- [website](https://linkedgeodata.org/)
	- their [releases](https://hobbitdata.informatik.uni-leipzig.de/LinkedGeoData/downloads.linkedgeodata.org/releases/) seem very old too, but hopefully we can run their code to get an up-to-date RDF
	- we could eventually experiment with their released graphs first

**Comment by doogyb** [comment]
We've agreed to use their [releases](https://hobbitdata.informatik.uni-leipzig.de/LinkedGeoData/downloads.linkedgeodata.org/releases/2015-11-02/) for now, as the LinkedGeoData software is old and would likely take some time to get running.
