### ISSUE TITLE
Create directory for ontologies

### ISSUE THREAD

**Issue by doogyb** [nestauk/ontologies#16]
This issue refers to the need to also group and track the ontology (in `owl` form) files that relate to the different data sources we're currently ingesting. 

This issue also relates to keeping track of the WebVOWL `.json` format versions of the ontologies, which might come in handy to avoid having to reconvert the original files down the line. It will also help to tightly couple both files.

We might want to rethink/confirm our naming conventions for `ontologies` vs. `taxonomies/data` vs `sparql queries`, as it could get confusing down the line. Strictly speaking, the ontologies are the "schemas" of the data, so we might want to come up with a definitive term to differentiate these schemas from the data itself. With that in mind, I think we need to rename/restructure some directories in the repository. Here is what I propose:

```
queries
  OSM
    stress
    explore
  Geonames
    stress
    explore
  ...
results
  OSM
    stress
    explore
  Geonames
    stress
    explore
  ...
ontologies
  OSM
    ontology.ttl
    ontology.json
  Geonames
    ontology.ttl
    ontology.json 
  ...
src
  OSM
    bin
  Geonames
    bin
  ...
data
  OSM
  Geonames
  ...
...
```

**Comment by doogyb** [comment]
Another way of doing this would be to put the datasources first and then each datasource has its own subdirs as above. Arguably a more intuitive approach, as we won't be mixing different data sources within directories... I think I prefer this approach to be honest, as it helps identify what is needed every time we add a new data source:

```
Geonames
  data
  ontologies
    ontology.ttl
    ontology.json
  queries
    stress
    explore
  results
    stress
    explore
  src
    bin
    ...

MeSH
  data
  ontologies
    ontology.ttl
    ontology.json
  queries
    stress
    explore
  results
    stress
    explore
  src
    bin
    ...
  ```

**Comment by mindrones** [comment]
We agreed on something like the below, subject to change if needed.

1) S3

All ontologies are/will be stored in S3 buckets similar to:

```
ontology-OSM-v1.0.0/
ontology-OSM-v2.0.0/
ontology-Geonames-v1.0.0/
...
```

2) EC2 instance:

we would have:
- `src/node_modules`: utils
- `src/ui`: a UI, initially for quick needs, later on for the explorer
- `src/bin`: scripts (js first, bash OK)
- `src/bin/[ontology]`: scripts for that `ontology`, on particular these can be specific to a particular DB tech
- `src/bin/all`: scripts to be run ion multiple ontologies, re-using more specific scripts
- `src/test`: scripts to test
	- data quality
	- performances
	- ?
- `graphs/ontologies-S3.yaml`:
	- 	a spec of where things are in S3, versions, etc
	- can be used as input for scripts, we'll have to discuss if OK using it as an output (e.g. to store the date of fetching)
- `graphs/vocabularies/`:
	- 	useful for vocabularies inspection
	- sources for our WEBVOWL instance
- `graphs/quality/`: queries and results to evaluate data quality
- `graphs/performances/`: queries and results to evaluate performances

Scripts should be executed by invoking npm scripts:

```
scripts: {
	...,
	gnq: 'node bin/gn/fetch && node test/Geonames/check-quality1'
}
```

Example structure:

```
src/
	node_modules/
		foo/
		fetching.js
		smthElse.js
	ui/
		node_modules/ // ignored
		package.json
		.../
	bin/
		Geonames/
			fetch.js
			cleanup.js
			ingest-neptune.sh|js
			ingest-virtuoso.sh|js
		MeSH/
			fetch.js
			enrich.js
			ingestNeptune.sh|js
			ingestVirtuoso.sh|js
		all/
			ingestGeonames.sh|js
			ingestMeSH.sh|js
			ingestAll.sh|js
	test/
		Geonames/
			check-quality1.js
		MeSH/
			check-quality1.js
graphs/
	ontologies-S3.yaml
	vocabularies/
		geonames-v1.0.0.ttl
		geonames-v1.0.0.json
		geonames-v2.0.0.ttl
		geonames-v2.0.0.json
		MeSH-v1.0.0.ttl
		MeSH-v1.0.0.json
	quality/
		Geonames/
			foo.rq
			foo1.json
			reports/
				quality1.json
				quality2.json
		MeSH/
			...
	perfs/
		Geonames/
		MeSH/
```
